clc
clear
close all
addpath("Code")
disp("=== FINAL CNN + Attention Training ===")
gpuDevice(1)
imds = imageDatastore("Dataset", ...
    IncludeSubfolders=true, ...
    LabelSource="foldernames", ...
    ReadFcn=@readAndSegment);

classes = categories(imds.Labels);
numClasses = numel(classes)
[imdsTrain,imdsVal] = splitEachLabel(imds,0.8,"randomized");
disp("Dataset split done")
augmenter = imageDataAugmenter( ...
    'RandRotation',[-15 15], ...
    'RandXTranslation',[-10 10], ...
    'RandYTranslation',[-10 10], ...
    'RandXScale',[0.9 1.1], ...
    'RandYScale',[0.9 1.1], ...
    'RandXReflection',true);
augTrain = augmentedImageDatastore([128 128],imdsTrain, ...
    DataAugmentation=augmenter);
augVal = augmentedImageDatastore([128 128],imdsVal);
net = resnet50;
inputSize = [128 128 3];
layers = layerGraph(net);
layers = replaceLayer(layers,"input_1", ...
    imageInputLayer([128 128 3], ...
    'Name',"input_1", ...
    'Normalization',"none"));

layerList = layers.Layers;
for i = 1:160
    layer = layerList(i);
    if isprop(layer,'WeightLearnRateFactor')
        layer.WeightLearnRateFactor = 0;
        layer.BiasLearnRateFactor = 0;
        layers = replaceLayer(layers,layer.Name,layer);
    end
end
newLayers = [
    fullyConnectedLayer(numClasses,"Name","fc_new")
    softmaxLayer("Name","softmax")
    classificationLayer("Name","output")
];
layers = replaceLayer(layers,"fc1000",newLayers(1));
layers = replaceLayer(layers,"fc1000_softmax",newLayers(2));
layers = replaceLayer(layers,"ClassificationLayer_fc1000",newLayers(3));
options = trainingOptions('adam', ...
    'MiniBatchSize',16, ...
    'MaxEpochs',5, ...
    'InitialLearnRate',1e-4, ...
    'Shuffle','every-epoch', ...
    'Plots','training-progress', ...
    'ExecutionEnvironment','gpu', ...
    'ValidationData',augVal, ...
    'ValidationFrequency',100, ...
    'Verbose',true, ...
    'ResetInputNormalization',false);
disp("Training started...")
netCNN = trainNetwork(augTrain,layers,options);
disp("Training finished")
if ~exist("Models","dir")
    mkdir("Models")
end
save("Models/CNN_Attention_Model.mat","netCNN","classes")
disp("Model saved")